import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { UserContextProvider } from "../context/userContext";
import { Inter } from "next/font/google";
import { Average } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

const average = Average({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Task Manager Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={average.className}>
        <UserContextProvider>
          <Toaster richColors position="top-right" />
          <div className="h-flex flex overflow-hidden"></div>
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
